# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\gitee\gitmanage\B000_study\B100_language\python\new_yysscript\src\ui\input_uuid_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uuid_win(object):
    def setupUi(self, uuid_win):
        uuid_win.setObjectName("uuid_win")
        uuid_win.resize(352, 153)
        self.verticalLayoutWidget = QtWidgets.QWidget(uuid_win)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_uuid = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_uuid.setObjectName("lb_uuid")
        self.horizontalLayout.addWidget(self.lb_uuid)
        self.le_uuid = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_uuid.setObjectName("le_uuid")
        self.horizontalLayout.addWidget(self.le_uuid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbtn_ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbtn_ok.setObjectName("pbtn_ok")
        self.horizontalLayout_2.addWidget(self.pbtn_ok)
        self.pbtn_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbtn_cancel.setObjectName("pbtn_cancel")
        self.horizontalLayout_2.addWidget(self.pbtn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(uuid_win)
        self.pbtn_cancel.clicked.connect(uuid_win.slot_pbtn_cancel_clicked)
        self.pbtn_ok.clicked.connect(uuid_win.slot_pbtn_ok_clicked)
        QtCore.QMetaObject.connectSlotsByName(uuid_win)

    def retranslateUi(self, uuid_win):
        _translate = QtCore.QCoreApplication.translate
        uuid_win.setWindowTitle(_translate("uuid_win", "Dialog"))
        self.lb_uuid.setText(_translate("uuid_win", "输入uuid:"))
        self.pbtn_ok.setText(_translate("uuid_win", "确认"))
        self.pbtn_cancel.setText(_translate("uuid_win", "取消"))
